from setuptools import setup, find_packages
setup(name='kmtnetpy',
      # scripts=['make_diff_image.py',
      #          'update_wcs.py',
      #          'update_wcs2.py',
      #          'update_wcs3.py',
      #          'combine_kmtnet.py',
      #          'find_sources.py',
      #          'update_cat_coord.py',
      #          'do_phot_cal.py',
      #          'update_cat_mag.py',
      #          'shorten_header.py',
      #          'get_center.py',
      #          'fetch_catalog.py',
      #          ],
      package_dir={'kmtnetpy': 'kmtnetpy'},
      packages=find_packages(),
      # package_data={'ksppy':['params/*']},
      )
